# Generated by Django 5.0.1 on 2025-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the user.', max_length=15, verbose_name='Phone Number'),
        ),
    ]
